# Generated by Django 5.2.4 on 2025-07-25 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('iso2_code', models.CharField(blank=True, max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('capital_city', models.CharField(blank=True, max_length=100)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('region_id', models.CharField(blank=True, max_length=10)),
                ('region_value', models.CharField(blank=True, max_length=100)),
                ('admin_region_id', models.CharField(blank=True, max_length=10)),
                ('admin_region_value', models.CharField(blank=True, max_length=100)),
                ('income_level_id', models.CharField(blank=True, max_length=10)),
                ('income_level_value', models.CharField(blank=True, max_length=100)),
                ('lending_type_id', models.CharField(blank=True, max_length=10)),
                ('lending_type_value', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=10)),
                ('source_value', models.CharField(blank=True, max_length=255)),
                ('source_note', models.TextField(blank=True)),
                ('source_organization', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HappinessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('ladder_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('upper_whisker', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('lower_whisker', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('explained_by_freedom_to_make_life_choices', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('explained_by_generosity', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('explained_by_perceptions_of_corruption', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('dystopia_plus_residual', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('explained_by_log_gdp_per_capita', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('explained_by_social_support', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('explained_by_healthy_life_expectancy', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='happiness_data', to='dashboard.country')),
            ],
            options={
                'ordering': ['-ladder_score', 'year', 'country_name'],
                'unique_together': {('country_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_iso3_code', models.CharField(blank=True, max_length=3)),
                ('date', models.CharField(max_length=4)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('obs_status', models.CharField(blank=True, max_length=10)),
                ('decimal_places', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators_data', to='dashboard.country')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_data', to='dashboard.indicator')),
            ],
            options={
                'ordering': ['country', 'indicator', 'date'],
                'unique_together': {('country', 'indicator', 'date')},
            },
        ),
    ]
